### ISSUE TITLE
Add `$NPM_TOKEN`

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/domparser-markdown#1]
Need an `$NPM_TOKEN` repository secret to make the `release-created.yml` workflow action _actually work_.

```yml
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
